name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./phone/pom.xml
          mvn clean package -f ./customer/pom.xml
          mvn clean package -f ./usim/pom.xml
          mvn clean package -f ./message/pom.xml
          mvn clean package -f ./report/pom.xml

      - name: Docker Build and push for Phone
        uses: docker/build-push-action@v4
        with:
          context: ./phone
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/phone:latest
            ghcr.io/${{ github.repository }}/phone:${{ github.ref_name }}
            
      - name: Docker Build and push for Customer
        uses: docker/build-push-action@v4
        with:
          context: ./customer
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/customer:latest
            ghcr.io/${{ github.repository }}/customer:${{ github.ref_name }}
            
      - name: Docker Build and push for Usim
        uses: docker/build-push-action@v4
        with:
          context: ./usim
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/usim:latest
            ghcr.io/${{ github.repository }}/usim:${{ github.ref_name }}
            
      - name: Docker Build and push for Message
        uses: docker/build-push-action@v4
        with:
          context: ./message
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/message:latest
            ghcr.io/${{ github.repository }}/message:${{ github.ref_name }}
            
      - name: Docker Build and push for Report
        uses: docker/build-push-action@v4
        with:
          context: ./report
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/report:latest
            ghcr.io/${{ github.repository }}/report:${{ github.ref_name }}
            
