server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: phone
          uri: http://localhost:8082
          predicates:
            - Path=/lostReportHistories/**, /devices/**, /lostReportStatusQueries/**, /searchPhoneInfos/**
        - id: customer
          uri: http://localhost:8083
          predicates:
            - Path=/customers/**, /searchCustomers/**
        - id: usim
          uri: http://localhost:8084
          predicates:
            - Path=/usims/**, /searchUsimStatuses/**
        - id: message
          uri: http://localhost:8085
          predicates:
            - Path=/usimBlockHistories/**, /verificationInfos/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: phone
          uri: http://phone:8080
          predicates:
            - Path=/lostReportHistories/**, /devices/**, 
        - id: customer
          uri: http://customer:8080
          predicates:
            - Path=/customers/**, 
        - id: usim
          uri: http://usim:8080
          predicates:
            - Path=/usims/**, 
        - id: message
          uri: http://message:8080
          predicates:
            - Path=/usimBlockHistories/**, /verificationInfos/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
