apiVersion: apps/v1
kind: Deployment
metadata:
  name: usim
  labels:
    app: usim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usim
  template:
    metadata:
      labels:
        app: usim
    spec:
      containers:
        - name: usim
          image: "username/usim:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
